// Build the site's own Pretendard subset: one variable woff2 that holds only the characters the
// pages actually use (static site → a few hundred Hangul syllables instead of 11,172).
//
//   npm run fonts      after changing page text; then commit public/fonts and the page heads
//
// Writes public/fonts/pretendard-site-<hash>.woff2 (+ .json manifest) and, in every page head, the
// <link rel="preload"> line plus an inline <style data-fonts> with the @font-face rules (no extra
// CSS request). Characters outside the subset fall back to
// the system font per glyph (e.g. text a visitor types into the fingerprint demo).
// `npm run harness` fails the "font-coverage" check when a page uses a character the subset lacks.
import subsetFont from 'subset-font';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PUB = join(ROOT, 'public');
const FONTS = join(PUB, 'fonts');
const CACHE = join(ROOT, 'node_modules', '.cache', 'datapd-fonts');
const SOURCE_URL = 'https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/packages/pretendard/dist/web/variable/woff2/PretendardVariable.woff2';
const SOURCE = join(CACHE, 'PretendardVariable-1.3.9.woff2');

// Always keep: printable ASCII, Latin-1 punctuation/symbols, typographic marks the copy uses.
const BASE_CHARS = String.fromCharCode(...Array.from({ length: 95 }, (_, i) => 0x20 + i))
  + '·—–…‘’“”«»→←↑↓×÷±©®™°₩€£¥§¶•‧※「」『』〈〉《》【】〔〕、。％＋－＝（）［］｛｝～·ㆍ';

export function siteFiles() {
  const out = [join(ROOT, 'index.html')];
  (function walk(d) {
    for (const n of readdirSync(d)) {
      const p = join(d, n);
      if (statSync(p).isDirectory()) { if (n !== 'fonts') walk(p); }
      else if (/\.(html|js|json)$/.test(n) && n !== 'sw.js') out.push(p);
    }
  })(PUB);
  return out;
}

// Characters the subset must cover: everything outside ASCII controls, from every page/script/registry.
export function siteChars(files = siteFiles()) {
  const set = new Set(BASE_CHARS);
  for (const f of files) for (const ch of readFileSync(f, 'utf8')) { const c = ch.codePointAt(0); if (c >= 0x20 && !(c >= 0x7f && c < 0xa0)) set.add(ch); }
  return set;
}

async function main() {
  if (!existsSync(SOURCE)) {
    mkdirSync(CACHE, { recursive: true });
    const r = await fetch(SOURCE_URL);
    if (!r.ok) throw new Error(`download failed ${r.status} ${SOURCE_URL}`);
    writeFileSync(SOURCE, Buffer.from(await r.arrayBuffer()));
  }
  const chars = [...siteChars()].sort((a, b) => a.codePointAt(0) - b.codePointAt(0)).join('');
  const hangul = [...chars].filter((c) => c >= '가' && c <= '힣').length;
  const out = await subsetFont(readFileSync(SOURCE), chars, { targetFormat: 'woff2' });
  const hash = createHash('sha256').update(out).digest('hex').slice(0, 10);
  const file = `pretendard-site-${hash}.woff2`;

  mkdirSync(FONTS, { recursive: true });
  for (const n of readdirSync(FONTS)) if (/^pretendard-site-[0-9a-f]+\.(woff2|json)$/.test(n)) rmSync(join(FONTS, n));
  writeFileSync(join(FONTS, file), out);
  writeFileSync(join(FONTS, file.replace('.woff2', '.json')), JSON.stringify({
    source: 'Pretendard Variable v1.3.9 (SIL OFL 1.1)', file, bytes: out.length, glyphs: [...chars].length, hangul, chars,
  }, null, 1) + '\n');

  // @font-face rules: the site subset + IBM Plex Mono (latin, latin-ext) — both self-hosted
  const plex = [400, 500, 600].flatMap((w) => [
    `@font-face{font-family:'IBM Plex Mono';font-style:normal;font-weight:${w};font-display:swap;src:url(/fonts/ibm-plex-mono/ibm-plex-mono-${w}-latin-ext.woff2) format('woff2');unicode-range:U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF}`,
    `@font-face{font-family:'IBM Plex Mono';font-style:normal;font-weight:${w};font-display:swap;src:url(/fonts/ibm-plex-mono/ibm-plex-mono-${w}-latin.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}`,
  ]);
  const fontCss = [
    `/* self-hosted fonts · generated by npm run fonts (scripts/subset-fonts.mjs) · Pretendard Variable v1.3.9 site subset, ${[...chars].length} chars · IBM Plex Mono · SIL OFL 1.1, see /fonts/ */`,
    `@font-face{font-family:'Pretendard Variable';font-style:normal;font-weight:45 920;font-display:swap;src:url(/fonts/${file}) format('woff2-variations'),url(/fonts/${file}) format('woff2')}`,
    ...plex,
  ];
  // Older builds linked a separate fonts.css; the rules now live inline in each head (one request less).
  rmSync(join(PUB, 'static', 'fonts.css'), { force: true });

  // every page head: preload the subset (downloads in parallel with site.css), then the inline rules
  const pages = siteFiles().filter((f) => f.endsWith('.html'));
  const preload = `<link rel="preload" href="/fonts/${file}" as="font" type="font/woff2" crossorigin />`;
  let touched = 0;
  for (const f of pages) {
    let s = readFileSync(f, 'utf8');
    const nl = s.includes('\r\n') ? '\r\n' : '\n';
    const before = s;
    const block = [preload, '<style data-fonts>', ...fontCss, '</style>'].join(nl);
    s = s.replace(/<link rel="preload" href="\/fonts\/pretendard-site-[0-9a-f]+\.woff2"[^>]*>\r?\n/g, '');
    s = s.replace(/<link rel="stylesheet" href="\/static\/fonts\.css" \/>|<style data-fonts>[\s\S]*?<\/style>/, () => block);
    if (!s.includes('<style data-fonts>')) throw new Error(`no font slot in ${f} (expected the fonts.css link or a <style data-fonts> block)`);
    if (s !== before) { writeFileSync(f, s); touched++; }
  }
  console.log(`✓ ${file}  ${out.length.toLocaleString()} B · ${[...chars].length} chars (${hangul} Hangul) · preload in ${touched}/${pages.length} pages`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) await main();
